development:
  cloud_name: hmkspkft9
  api_key: '245717352691178'
  api_secret: IdJzAwKW2-MYFaRZ2tIAu_PciAw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hmkspkft9
  api_key: '245717352691178'
  api_secret: IdJzAwKW2-MYFaRZ2tIAu_PciAw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hmkspkft9
  api_key: '245717352691178'
  api_secret: IdJzAwKW2-MYFaRZ2tIAu_PciAw
  enhance_image_tag: true
  static_image_support: false